### ISSUE TITLE
Received text via mqtt not accepted

### ISSUE THREAD

**Issue by Jonny87** [ioBroker/ioBroker.mqtt#9] opened 2018-01-09 17:04 UTC
I tried to receive owntracks values via mqtt (cloudmqtt).

The sent text looks like:

{"_type":"location","tid":"pn","acc":19,"batt":0,"lat":xx.6933686,"lon":x.422188,"t":"u","tst":1515319324}

On data point only "undefined" will be showed.

If I send an text like:

{"_type":"location","tid":"pn","acc":19,"batt":0,"lat":xx.6933686,"lon":x.422188,"t":"u","tst":1515319324

without curly bracket "}" at the end, then it works.

**Comment by Apollon77** [comment] 2018-02-09 09:27
Formally with removing the curly bracket "}" at the end you render the message to be invalid. Interesting that this can work at all.

What datatype is the target datapoint? if it is mixed can you please try to change to String and retry?

**Comment by ManuelW77** [comment] 2018-03-31 21:31
Hey there, i have the same problem.
If i send a msg with " the mqtt adapter won't accept it.
{"tool":20} gives no data in iobroker

but, if i remove the " or change it to ' the message arrives. 
And the message also arrives, if i send it with " and remove the closing curly bracket.

So i think there is a problem with messages that includes ".

PS: i try'd with all datatypes.

**Comment by GermanBluefox** [comment] 2018-07-06 21:18
Fixed in 2.0.1

**Comment by ManuelW77** [comment] 2018-11-14 08:04
Hey GermanBluefox, I have v2.0.3 and the problem is already there.

**Comment by Apollon77** [comment] 2018-12-01 16:04
Can we see some debug logs?

**Closed** 2020-06-27 16:19 UTC
Labels: question, wontfix
